[tools]
java = "zulu-25"

[tasks.build]
run = "./gradlew build"

[tasks.run]
run = "./gradlew :compose-glfw-demo:run"

[tasks.run-wayland]
run = "./gradlew :compose-glfw-demo:runWayland"

[tasks.run-x11]
run = "./gradlew :compose-glfw-demo:runX11"
